/*
 * Copyright (C) 2023 lucamannocci
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package jrivitscreen;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author lucamannocci
 */
public class MainJFrame extends javax.swing.JFrame {

  private int indicaSceltaLavoro;
  private ImageIcon Img_Exit, Img_Ok, Img_Nulla, Img_Freccia_su, Img_Freccia_giu, Img_Warning, Img_Setup, Img_Play;
  private Worker w_mf;

  /**
   * Creates new form MainJFrame
   */
  public MainJFrame() {
    initComponents();
    this.jPanelMain.setVisible(true);
    this.jPanelStart.setVisible(false);
    this.jPanelSetup.setVisible(false);
    this.jPanelStarted.setVisible(false);
    this.jPanelSetupLan.setVisible(false);
    this.jPanelSetupWifi.setVisible(false);
    this.JPanelWarning.setVisible(false);
    this.JPanelInfo.setVisible(false);
    this.jLabel_B_3.setText("main");
    this.indicaSceltaLavoro = 0;
    Img_Exit = new javax.swing.ImageIcon(getClass().getResource("/jrivitscreen/images/exit.png"));
    Img_Ok = new javax.swing.ImageIcon(getClass().getResource("/jrivitscreen/images/ok.png"));
    Img_Nulla = new javax.swing.ImageIcon(getClass().getResource("/jrivitscreen/images/nulla.png"));
    Img_Freccia_su = new javax.swing.ImageIcon(getClass().getResource("/jrivitscreen/images/freccia_su.png"));
    Img_Freccia_giu = new javax.swing.ImageIcon(getClass().getResource("/jrivitscreen/images/freccia_giu.png"));
    Img_Warning = new javax.swing.ImageIcon(getClass().getResource("/jrivitscreen/images/warning.png"));
    Img_Setup = new javax.swing.ImageIcon(getClass().getResource("/jrivitscreen/images/setup.png"));
    Img_Play = new javax.swing.ImageIcon(getClass().getResource("/jrivitscreen/images/play.png"));
    //inizio in n Main
    w_mf = new Worker(this);
    w_mf.set_operation("start");
    try {
      w_mf.doInBackground();
    } catch (Exception ex) {
      Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
    }
    this.jPanelMain.setVisible(true);
    this.change_buttons(Img_Warning, Img_Nulla, Img_Setup, Img_Play,
            Img_Nulla, Img_Nulla);
    this.jLabel_B_3.setText("main");

//Guardare se esiste un file con l'ultima scelta lavoro precedente ?
//Leggere al file lista lavori e aggiornare elenco lavori
//Leggere dal file configurazione Lan Wifi 
//Leggere dal file i warning
//Leggere la info
//Leggere stato aria in ingresso 
//Leggere stato aria al Tools
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelLeft = new javax.swing.JPanel();
        jButton_L_1 = new javax.swing.JButton();
        jButton_L_2 = new javax.swing.JButton();
        jButton_L_3 = new javax.swing.JButton();
        jLayeredPaneMain = new javax.swing.JLayeredPane();
        jPanelMain = new javax.swing.JPanel();
        jLabelLogo = new javax.swing.JLabel();
        jPanelStart = new javax.swing.JPanel();
        jScrollPaneListaLavori = new javax.swing.JScrollPane();
        jListLavori = new javax.swing.JList<>();
        jPanelSetup = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanelSetupWifi = new javax.swing.JPanel();
        jScrollPaneListaLavori2 = new javax.swing.JScrollPane();
        jListSetupWifi = new javax.swing.JList<>();
        jPanelSetupLan = new javax.swing.JPanel();
        jScrollPaneListaLavori3 = new javax.swing.JScrollPane();
        jListSetupLan = new javax.swing.JList<>();
        jPanelStarted = new javax.swing.JPanel();
        jLabelStartedContatore = new javax.swing.JLabel();
        jLabelStartedNomeDevice = new javax.swing.JLabel();
        jLabelStartedNomeLavoro = new javax.swing.JLabel();
        jProgressBarStarted = new javax.swing.JProgressBar();
        jLabelStartedErrati = new javax.swing.JLabel();
        jLabelStartedTiri = new javax.swing.JLabel();
        JPanelWarning = new javax.swing.JPanel();
        jScrollPaneListaLavori5 = new javax.swing.JScrollPane();
        jListLavori5 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaWarningInfo1 = new javax.swing.JTextArea();
        JPanelInfo = new javax.swing.JPanel();
        jScrollPaneListaLavori6 = new javax.swing.JScrollPane();
        jListLavori6 = new javax.swing.JList<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanelRight = new javax.swing.JPanel();
        jButton_R_1 = new javax.swing.JButton();
        jButton_R_2 = new javax.swing.JButton();
        jButton_R_3 = new javax.swing.JButton();
        jPanelBotton = new javax.swing.JPanel();
        jLabel_B_1 = new javax.swing.JLabel();
        jLabel_B_2 = new javax.swing.JLabel();
        jLabel_B_3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));
        setMaximumSize(new java.awt.Dimension(480, 320));
        setMinimumSize(new java.awt.Dimension(480, 320));
        setName("frameMain"); // NOI18N
        setPreferredSize(new java.awt.Dimension(480, 320));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelLeft.setBackground(new java.awt.Color(255, 255, 255));
        jPanelLeft.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelLeft.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton_L_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jrivitscreen/images/nulla.png"))); // NOI18N
        jButton_L_1.setPreferredSize(new java.awt.Dimension(61, 62));
        jButton_L_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_L_1ActionPerformed(evt);
            }
        });
        jPanelLeft.add(jButton_L_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, -1, -1));

        jButton_L_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jrivitscreen/images/nulla.png"))); // NOI18N
        jButton_L_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_L_2ActionPerformed(evt);
            }
        });
        jPanelLeft.add(jButton_L_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 73, -1, -1));

        jButton_L_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jrivitscreen/images/nulla.png"))); // NOI18N
        jButton_L_3.setPreferredSize(new java.awt.Dimension(61, 62));
        jButton_L_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_L_3ActionPerformed(evt);
            }
        });
        jPanelLeft.add(jButton_L_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, -1, -1));

        getContentPane().add(jPanelLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 0, 60, 260));

        jLayeredPaneMain.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLayeredPaneMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelMain.setBackground(new java.awt.Color(255, 255, 255));
        jPanelMain.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelMain.setMinimumSize(new java.awt.Dimension(340, 260));
        jPanelMain.setOpaque(false);
        jPanelMain.setPreferredSize(new java.awt.Dimension(340, 260));
        jPanelMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jrivitscreen/images/logori.png"))); // NOI18N
        jPanelMain.add(jLabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 230, 230));

        jLayeredPaneMain.add(jPanelMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 260));

        jPanelStart.setBackground(new java.awt.Color(255, 255, 153));
        jPanelStart.setMinimumSize(new java.awt.Dimension(340, 260));
        jPanelStart.setOpaque(false);
        jPanelStart.setPreferredSize(new java.awt.Dimension(340, 260));
        jPanelStart.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPaneListaLavori.setBackground(new java.awt.Color(204, 204, 255));
        jScrollPaneListaLavori.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPaneListaLavori.setPreferredSize(new java.awt.Dimension(175, 180));

        jListLavori.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Lavoro1", "Lavoro 2", "Lavoro 3", "Lavoro 4", "Lavoro 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListLavori.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListLavori.setToolTipText("Works");
        jListLavori.setPreferredSize(new java.awt.Dimension(160, 160));
        jListLavori.setVisibleRowCount(10);
        jScrollPaneListaLavori.setViewportView(jListLavori);

        jPanelStart.add(jScrollPaneListaLavori, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 5, -1, -1));

        jLayeredPaneMain.add(jPanelStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 260));

        jPanelSetup.setBackground(new java.awt.Color(51, 51, 0));
        jPanelSetup.setMinimumSize(new java.awt.Dimension(340, 260));
        jPanelSetup.setOpaque(false);
        jPanelSetup.setPreferredSize(new java.awt.Dimension(340, 260));
        jPanelSetup.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lao MN", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 0));
        jLabel1.setText("Info System");
        jLabel1.setAutoscrolls(true);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelSetup.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 120, 110, -1));

        jLabel2.setFont(new java.awt.Font("Lao MN", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 204, 0));
        jLabel2.setText("Network Setup");
        jLabel2.setAutoscrolls(true);
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelSetup.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 50, 140, -1));

        jLayeredPaneMain.add(jPanelSetup, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 260));

        jPanelSetupWifi.setBackground(new java.awt.Color(0, 153, 153));
        jPanelSetupWifi.setMinimumSize(new java.awt.Dimension(340, 260));
        jPanelSetupWifi.setOpaque(false);
        jPanelSetupWifi.setPreferredSize(new java.awt.Dimension(340, 260));
        jPanelSetupWifi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPaneListaLavori2.setBackground(new java.awt.Color(204, 204, 255));
        jScrollPaneListaLavori2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPaneListaLavori2.setPreferredSize(new java.awt.Dimension(175, 180));

        jListSetupWifi.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "For Config AP", "Client Wifi", "Radio OFF" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListSetupWifi.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListSetupWifi.setToolTipText("wifi setup");
        jListSetupWifi.setPreferredSize(new java.awt.Dimension(160, 160));
        jListSetupWifi.setVisibleRowCount(10);
        jScrollPaneListaLavori2.setViewportView(jListSetupWifi);

        jPanelSetupWifi.add(jScrollPaneListaLavori2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, 170));

        jLayeredPaneMain.add(jPanelSetupWifi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 260));

        jPanelSetupLan.setBackground(new java.awt.Color(0, 102, 102));
        jPanelSetupLan.setMinimumSize(new java.awt.Dimension(340, 260));
        jPanelSetupLan.setOpaque(false);
        jPanelSetupLan.setPreferredSize(new java.awt.Dimension(340, 260));

        jScrollPaneListaLavori3.setBackground(new java.awt.Color(204, 204, 255));
        jScrollPaneListaLavori3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPaneListaLavori3.setPreferredSize(new java.awt.Dimension(230, 180));
        jScrollPaneListaLavori3.setRequestFocusEnabled(false);

        jListSetupLan.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "DHCP", "STATIC", "FACTORY DEF. 192.168.207.1" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListSetupLan.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListSetupLan.setToolTipText("Works");
        jListSetupLan.setPreferredSize(new java.awt.Dimension(200, 160));
        jListSetupLan.setVisibleRowCount(10);
        jScrollPaneListaLavori3.setViewportView(jListSetupLan);

        jPanelSetupLan.add(jScrollPaneListaLavori3);

        jLayeredPaneMain.add(jPanelSetupLan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 260));

        jPanelStarted.setBackground(new java.awt.Color(0, 255, 0));
        jPanelStarted.setMinimumSize(new java.awt.Dimension(340, 260));
        jPanelStarted.setOpaque(false);
        jPanelStarted.setPreferredSize(new java.awt.Dimension(340, 260));
        jPanelStarted.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelStartedContatore.setFont(new java.awt.Font("Lao MN", 0, 26)); // NOI18N
        jLabelStartedContatore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelStartedContatore.setText("10/20");
        jLabelStartedContatore.setToolTipText("");
        jLabelStartedContatore.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelStarted.add(jLabelStartedContatore, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 320, 40));

        jLabelStartedNomeDevice.setFont(new java.awt.Font("Lao MN", 0, 18)); // NOI18N
        jLabelStartedNomeDevice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelStartedNomeDevice.setText("Device AAA");
        jLabelStartedNomeDevice.setToolTipText("");
        jLabelStartedNomeDevice.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelStarted.add(jLabelStartedNomeDevice, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 10, 320, -1));

        jLabelStartedNomeLavoro.setFont(new java.awt.Font("Lao MN", 0, 18)); // NOI18N
        jLabelStartedNomeLavoro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelStartedNomeLavoro.setText("Lavoro 1");
        jLabelStartedNomeLavoro.setToolTipText("");
        jLabelStartedNomeLavoro.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelStarted.add(jLabelStartedNomeLavoro, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 50, 320, -1));

        jProgressBarStarted.setToolTipText("");
        jProgressBarStarted.setValue(30);
        jProgressBarStarted.setAutoscrolls(true);
        jProgressBarStarted.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jProgressBarStarted.setOpaque(true);
        jPanelStarted.add(jProgressBarStarted, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 400, 30));

        jLabelStartedErrati.setBackground(new java.awt.Color(255, 51, 51));
        jLabelStartedErrati.setText("Errati 1");
        jLabelStartedErrati.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelStartedErrati.setOpaque(true);
        jPanelStarted.add(jLabelStartedErrati, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, -1, -1));

        jLabelStartedTiri.setText("Validi 9");
        jLabelStartedTiri.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelStartedTiri.setOpaque(true);
        jPanelStarted.add(jLabelStartedTiri, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLayeredPaneMain.add(jPanelStarted, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 260));

        JPanelWarning.setBackground(new java.awt.Color(255, 102, 51));
        JPanelWarning.setPreferredSize(new java.awt.Dimension(358, 260));
        JPanelWarning.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPaneListaLavori5.setBackground(new java.awt.Color(204, 204, 255));
        jScrollPaneListaLavori5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPaneListaLavori5.setPreferredSize(new java.awt.Dimension(175, 180));

        jListLavori5.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "warning 1", "Warning 2", "Warning 3", "Warning 4", "Warning 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListLavori5.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListLavori5.setToolTipText("Works");
        jListLavori5.setPreferredSize(new java.awt.Dimension(160, 160));
        jListLavori5.setVisibleRowCount(10);
        jScrollPaneListaLavori5.setViewportView(jListLavori5);

        JPanelWarning.add(jScrollPaneListaLavori5, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 5, 270, 170));

        jTextAreaWarningInfo1.setColumns(20);
        jTextAreaWarningInfo1.setRows(5);
        jScrollPane2.setViewportView(jTextAreaWarningInfo1);

        JPanelWarning.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 185, 270, 60));

        jLayeredPaneMain.add(JPanelWarning, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 358, 260));

        JPanelInfo.setBackground(new java.awt.Color(204, 204, 255));
        JPanelInfo.setPreferredSize(new java.awt.Dimension(358, 260));
        JPanelInfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPaneListaLavori6.setBackground(new java.awt.Color(204, 204, 255));
        jScrollPaneListaLavori6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPaneListaLavori6.setPreferredSize(new java.awt.Dimension(175, 180));

        jListLavori6.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "info 1", "info 2", "info 3", "info 4", "info 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListLavori6.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListLavori6.setToolTipText("Works");
        jListLavori6.setPreferredSize(new java.awt.Dimension(160, 160));
        jListLavori6.setVisibleRowCount(10);
        jScrollPaneListaLavori6.setViewportView(jListLavori6);

        JPanelInfo.add(jScrollPaneListaLavori6, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 5, 270, -1));

        jScrollPane1.setBackground(new java.awt.Color(204, 204, 255));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        JPanelInfo.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 190, 270, -1));

        jLayeredPaneMain.add(JPanelInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 358, 260));

        getContentPane().add(jLayeredPaneMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 0, 358, 260));

        jPanelRight.setBackground(new java.awt.Color(255, 255, 255));
        jPanelRight.setOpaque(false);

        jButton_R_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jrivitscreen/images/nulla.png"))); // NOI18N
        jButton_R_1.setBorderPainted(false);
        jButton_R_1.setContentAreaFilled(false);
        jButton_R_1.setPreferredSize(new java.awt.Dimension(61, 62));
        jButton_R_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_R_1ActionPerformed(evt);
            }
        });
        jPanelRight.add(jButton_R_1);

        jButton_R_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jrivitscreen/images/nulla.png"))); // NOI18N
        jButton_R_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_R_2ActionPerformed(evt);
            }
        });
        jPanelRight.add(jButton_R_2);

        jButton_R_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jrivitscreen/images/nulla.png"))); // NOI18N
        jButton_R_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_R_3ActionPerformed(evt);
            }
        });
        jPanelRight.add(jButton_R_3);

        getContentPane().add(jPanelRight, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 60, 260));

        jPanelBotton.setBackground(new java.awt.Color(204, 204, 255));
        jPanelBotton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelBotton.setPreferredSize(new java.awt.Dimension(475, 38));

        jLabel_B_1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel_B_1.setText("10:12");
        jPanelBotton.add(jLabel_B_1);

        jLabel_B_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_B_2.setText("Message");
        jLabel_B_2.setPreferredSize(new java.awt.Dimension(120, 16));
        jPanelBotton.add(jLabel_B_2);

        jLabel_B_3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_B_3.setText("main");
        jPanelBotton.add(jLabel_B_3);

        getContentPane().add(jPanelBotton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 480, 32));

        pack();
    }// </editor-fold>//GEN-END:initComponents

  private void jButton_R_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_R_1ActionPerformed
    // Alla pressione del primo tasto in alto:
    switch (this.jLabel_B_3.getText()) {
      case "main":
        //Sono in Main vado in Start
        this.jPanelMain.setVisible(false);
        this.jPanelStart.setVisible(true);
        this.change_buttons(Img_Exit, Img_Nulla, Img_Nulla, Img_Freccia_su,
                Img_Freccia_giu, Img_Nulla);
        this.jLabel_B_3.setText("start");
        this.jListLavori.setSelectedIndex(this.indicaSceltaLavoro);//prima scelta      
        break;
      case "started":
        //Sono in Started vado in Start Premuto Stop
        this.jPanelStarted.setVisible(false);
        this.jPanelStart.setVisible(true);
        this.change_buttons(Img_Exit, Img_Nulla, Img_Nulla, Img_Freccia_su,
                Img_Freccia_giu, Img_Nulla);
        this.jLabel_B_3.setText("start");
        break;
      case "setup":
        //Sono in Setup vado in Setup Lan
        this.jPanelSetup.setVisible(false);
        this.jPanelSetupLan.setVisible(true);
        this.change_buttons(Img_Exit, Img_Nulla, Img_Nulla, Img_Freccia_su,
                Img_Freccia_giu, Img_Ok);
        this.jLabel_B_3.setText("setup lan");
        break;
    }

    if (this.jLabel_B_3.getText().equalsIgnoreCase("start")) {
      int posizioneLista = this.jListLavori.getAnchorSelectionIndex();
      if (posizioneLista > 0) {
        posizioneLista--;
        this.jListLavori.setSelectedIndex(posizioneLista);
      } else {
        this.jListLavori.setSelectedIndex(this.indicaSceltaLavoro);//prima scelta
      }
    }
    if (this.jLabel_B_3.getText().equalsIgnoreCase("setup lan")) {
      int posizioneLista = this.jListSetupLan.getAnchorSelectionIndex();
      if (posizioneLista > 0) {
        posizioneLista--;
        this.jListSetupLan.setSelectedIndex(posizioneLista);
      }
    }
    if (this.jLabel_B_3.getText().equalsIgnoreCase("setup wifi")) {
      int posizioneLista = this.jListSetupWifi.getAnchorSelectionIndex();
      if (posizioneLista > 0) {
        posizioneLista--;
        this.jListSetupWifi.setSelectedIndex(posizioneLista);
      }
    }
  }//GEN-LAST:event_jButton_R_1ActionPerformed

  private void jButton_R_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_R_2ActionPerformed
    // Secondo pulsante di sx a partire dall'alto:
    int posizioneLista = 0;
    int limiteLista = 0;

    switch (this.jLabel_B_3.getText()) {
      case "start":
        posizioneLista = this.jListLavori.getAnchorSelectionIndex();
        limiteLista = this.jListLavori.getComponentCount();
        if (posizioneLista < limiteLista) {
          posizioneLista++;
          this.jListLavori.setSelectedIndex(posizioneLista);
        }
        break;
      case "started":
        //Sono in Started premuto Pause vado in Start
        this.jPanelStarted.setVisible(false);
        this.jPanelStart.setVisible(true);
        jButton_L_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jrivitscreen/images/exit.png"))); // NOI18N
        jButton_L_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jrivitscreen/images/nulla.png"))); // NOI18N
        jButton_R_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jrivitscreen/images/freccia_su.png"))); // NOI18N
        jButton_R_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jrivitscreen/images/freccia_giu.png"))); // NOI18N
        this.jLabel_B_3.setText("start");
        break;
      case "setup lan":
        posizioneLista = this.jListSetupLan.getAnchorSelectionIndex();
        limiteLista = this.jListSetupLan.getComponentCount();
        if (posizioneLista < limiteLista) {
          posizioneLista++;
          this.jListSetupLan.setSelectedIndex(posizioneLista);
        }
        break;
      case "setup wifi":
        posizioneLista = this.jListSetupWifi.getAnchorSelectionIndex();
        limiteLista = this.jListSetupWifi.getComponentCount();
        if (posizioneLista < limiteLista) {
          posizioneLista++;
          this.jListSetupWifi.setSelectedIndex(posizioneLista);
        }
        break;
    }


  }//GEN-LAST:event_jButton_R_2ActionPerformed

  private void jButton_L_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_L_1ActionPerformed
    // Controllo il focus del pannello:

    switch (this.jLabel_B_3.getText()) {
      case "main":
        //vado in Panel Warning
        this.jPanelMain.setVisible(false);
        this.JPanelWarning.setVisible(true);
        jButton_L_1.setIcon(this.Img_Exit);
        jButton_L_2.setIcon(this.Img_Nulla);
        jButton_L_3.setIcon(this.Img_Nulla);
        jButton_R_1.setIcon(this.Img_Freccia_su);
        jButton_R_2.setIcon(this.Img_Freccia_giu);
        jButton_R_3.setIcon(this.Img_Nulla);
        this.jLabel_B_3.setText("warning");
        break;
      case "start":
        //Sono in start devo tornare in Main
        this.jPanelStart.setVisible(false);
        this.jPanelMain.setVisible(true);
        this.change_buttons(Img_Exit, Img_Nulla, Img_Nulla, Img_Freccia_su,
                Img_Freccia_giu, Img_Nulla);
        this.jLabel_B_3.setText("main");
        break;
      case "warning":
        //torno in Panel Main
        this.JPanelWarning.setVisible(false);
        this.jPanelMain.setVisible(true);
        this.change_buttons(Img_Warning, Img_Nulla, Img_Setup, this.Img_Play,
                Img_Nulla, Img_Nulla);
        this.jLabel_B_3.setText("main");
        break;
      case "setup":
        //torno in Panel Main
        this.jPanelSetup.setVisible(false);
        this.jPanelMain.setVisible(true);
        this.change_buttons(Img_Warning, Img_Nulla, Img_Setup, Img_Play,
                Img_Nulla, Img_Nulla);
        this.jLabel_B_3.setText("main");
        break;
      case "setup lan":
        //torno in Panel Setup
        this.jPanelSetupLan.setVisible(false);
        this.jPanelSetup.setVisible(true);
        this.jLabel_B_3.setText("setup");
        break;
      case "setup wifi":
        //torno in Panel Setup
        this.jPanelSetupWifi.setVisible(false);
        this.jPanelSetup.setVisible(true);
        this.jLabel_B_3.setText("setup");
        break;
      case "info":
        //Sono in info tornare in setup
        this.JPanelInfo.setVisible(false);
        this.jPanelSetup.setVisible(true);
        this.change_buttons(Img_Exit, Img_Nulla, Img_Nulla, Img_Nulla,
                Img_Nulla, Img_Nulla);
        this.jLabel_B_3.setText("setup");
        break;

    }

  }//GEN-LAST:event_jButton_L_1ActionPerformed

  private void jButton_L_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_L_3ActionPerformed
    //Pulsante Left terzo
    switch (this.jLabel_B_3.getText()) {
      case "main":
        //go to Panel Setup
        this.jPanelMain.setVisible(false);
        this.jPanelSetup.setVisible(true);
        this.change_buttons(Img_Exit, Img_Nulla, Img_Nulla, Img_Nulla,
                Img_Nulla, Img_Nulla);
        this.jLabel_B_3.setText("setup");
        break;
    }

  }//GEN-LAST:event_jButton_L_3ActionPerformed

  private void jButton_R_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_R_3ActionPerformed
   
    switch (this.jLabel_B_3.getText()) {
      case "start":
        //go to Panel Started
      this.jPanelStart.setVisible(false);
      this.jPanelStarted.setVisible(true);
        this.change_buttons(Img_Exit, Img_Ok, Img_Nulla, Img_Nulla,
                Img_Nulla, Img_Nulla);
      this.jLabel_B_3.setText("started");
        break;
    }    
  }//GEN-LAST:event_jButton_R_3ActionPerformed

  private void jButton_L_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_L_2ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jButton_L_2ActionPerformed

  /**
   * @param args the command line arguments
   */
  @SuppressWarnings("empty-statement")
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      @Override
      public void run() {
        MainJFrame mf = new MainJFrame();
        mf.setVisible(true);
      }
    });
  }

  /**
   * Setup dei pulsanti
   */
  private void change_buttons(ImageIcon I1, ImageIcon I2, ImageIcon I3,
          ImageIcon I4, ImageIcon I5, ImageIcon I6) {
    jButton_L_1.setIcon(I1);
    jButton_L_2.setIcon(I2);
    jButton_L_3.setIcon(I3);
    jButton_R_1.setIcon(I4);
    jButton_R_2.setIcon(I5);
    jButton_R_3.setIcon(I6);
  }

  /**
   * *
   * Metodo per display data e ora
   *
   * @data la stringa data time
   */
  public void setjLabel_B_1(String data) {
    this.jLabel_B_1.setText(data);
  }

  /**
   * Metodo per prendere l'imput dai pulsanti fisici
   *
   * @p String nome pulsante
   */
  public void pulsante_hw(String p) {
    switch (p) {
      case "PL1":
        jButton_L_1ActionPerformed(null);
        break;
      case "PL2":
        jButton_L_2ActionPerformed(null);
        break;
      case "PL3":
        jButton_L_3ActionPerformed(null);
        break;
      case "PR1":
        jButton_R_1ActionPerformed(null);
        break;
      case "PR2":
        jButton_R_2ActionPerformed(null);
        break;
      case "PR3":
        jButton_R_3ActionPerformed(null);
        break;
    }
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanelInfo;
    private javax.swing.JPanel JPanelWarning;
    private javax.swing.JButton jButton_L_1;
    private javax.swing.JButton jButton_L_2;
    private javax.swing.JButton jButton_L_3;
    private javax.swing.JButton jButton_R_1;
    private javax.swing.JButton jButton_R_2;
    private javax.swing.JButton jButton_R_3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelStartedContatore;
    private javax.swing.JLabel jLabelStartedErrati;
    private javax.swing.JLabel jLabelStartedNomeDevice;
    private javax.swing.JLabel jLabelStartedNomeLavoro;
    private javax.swing.JLabel jLabelStartedTiri;
    private javax.swing.JLabel jLabel_B_1;
    private javax.swing.JLabel jLabel_B_2;
    private javax.swing.JLabel jLabel_B_3;
    private javax.swing.JLayeredPane jLayeredPaneMain;
    private javax.swing.JList<String> jListLavori;
    private javax.swing.JList<String> jListLavori5;
    private javax.swing.JList<String> jListLavori6;
    private javax.swing.JList<String> jListSetupLan;
    private javax.swing.JList<String> jListSetupWifi;
    private javax.swing.JPanel jPanelBotton;
    private javax.swing.JPanel jPanelLeft;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JPanel jPanelRight;
    private javax.swing.JPanel jPanelSetup;
    private javax.swing.JPanel jPanelSetupLan;
    private javax.swing.JPanel jPanelSetupWifi;
    private javax.swing.JPanel jPanelStart;
    private javax.swing.JPanel jPanelStarted;
    private javax.swing.JProgressBar jProgressBarStarted;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPaneListaLavori;
    private javax.swing.JScrollPane jScrollPaneListaLavori2;
    private javax.swing.JScrollPane jScrollPaneListaLavori3;
    private javax.swing.JScrollPane jScrollPaneListaLavori5;
    private javax.swing.JScrollPane jScrollPaneListaLavori6;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextAreaWarningInfo1;
    // End of variables declaration//GEN-END:variables

}
