srvkey=AAAASSSDDDD
data_versione=07/06/2024
versione=0.306
ip_db="127.0.0.1"
pathWatch=/tmp/CT/
# attenzione ! l'aggiunta delle librerie PI4J \u00e8 molto delicata. Occorre che siano 
# presenti almeno core, library.pigpio, plugin.pigpio, sfl4j-api e sfl4j-simple
# attenzione ! Se nel file /etc/hosts non c'\u00e8 l'abbinamento 127.0.0.1 con localhost
# la connessione jdbc:mariadb://localhost:3306 richiede molto pi\u00f9
# tempo per essere aperta
# Per sicurezza, meglio usare:
db=jdbc:mariadb://127.0.0.1:3306
db_name=rivit
db_user=DrivitB
db_pwd=%%DBRivit

