/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package s7guiTest;

import static Moka7.S7Client.errTCPDataRecvTout;
import java.awt.Color;
import java.io.IOException;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JButton;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;

/**
 *
 * @author Luca
 */
public class JConsole extends javax.swing.JFrame {

    private JS7Test s7;
    private Timer timer;
    private final int DB1 = 1;
    private final int DB2 = 2;
    private final int DB3 = 3;
    private final int DB4 = 4;

    /**
     * Creates new form JConsole
     */
    public JConsole() {
        s7 = new JS7Test();
        initComponents();

        this.jButtonReadDB1.setEnabled(false);
        this.jButtonWriteDB2.setEnabled(false);
        this.jButtonReadDB3.setEnabled(false);
        this.jButtonReadDB4.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelledStato = new javax.swing.JPanel();
        jLabelSelectW = new javax.swing.JLabel();
        jLabelSelectWL = new javax.swing.JLabel();
        jButtonWriteWork = new javax.swing.JButton();
        jTextSelectWork = new javax.swing.JTextField();
        jButtonWriteWL = new javax.swing.JButton();
        jTextSelectWL = new javax.swing.JTextField();
        jLabelStatus = new javax.swing.JLabel();
        jTextStatus = new javax.swing.JTextField();
        jTextStatusHEX = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelLAV_NO = new javax.swing.JLabel();
        jLabelLAV_UNC = new javax.swing.JLabel();
        jLabelLAV_RDY = new javax.swing.JLabel();
        jLabelLAV_STR = new javax.swing.JLabel();
        jLabelLAV_DONE = new javax.swing.JLabel();
        jLabelWL_UNC = new javax.swing.JLabel();
        jLabelWL_RDY = new javax.swing.JLabel();
        jLabelWL_STR = new javax.swing.JLabel();
        jLabelCT_GO = new javax.swing.JLabel();
        jLabelCT_FLAGAIR_ON = new javax.swing.JLabel();
        jLabelCT_ALR = new javax.swing.JLabel();
        jLabelCT_YEL = new javax.swing.JLabel();
        jLabelCT_LOCK = new javax.swing.JLabel();
        jLabelCT_RUN = new javax.swing.JLabel();
        jLabelCT_STOPPD = new javax.swing.JLabel();
        jLabelWL_DONE = new javax.swing.JLabel();
        jLabelRispostaRivettoErr = new javax.swing.JLabel();
        jButtonRispTiroErrOK = new javax.swing.JButton();
        jButtonRispTiroErrAnnulla = new javax.swing.JButton();
        jButtonRispTiroErrAccetta = new javax.swing.JButton();
        jButtonStop = new javax.swing.JButton();
        jButtonPause = new javax.swing.JButton();
        jLabelConnectedLedRosso = new javax.swing.JLabel();
        jLabelConnectedLedGiallo = new javax.swing.JLabel();
        jLabelConnectedLedVerde = new javax.swing.JLabel();
        jLabelConnectedLedBlu = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelDB1 = new javax.swing.JLabel();
        jComboBoxDB1 = new javax.swing.JComboBox<>();
        jTextFieldDB1 = new javax.swing.JTextField();
        jButtonReadDB1 = new javax.swing.JButton();
        jLabelDB2 = new javax.swing.JLabel();
        jComboBoxDB2 = new javax.swing.JComboBox<>();
        jButtonWriteDB2 = new javax.swing.JButton();
        jTextFieldDB2 = new javax.swing.JTextField();
        jLabelDB3 = new javax.swing.JLabel();
        jComboBoxDB3 = new javax.swing.JComboBox<>();
        jButtonReadDB3 = new javax.swing.JButton();
        jTextFieldDB3 = new javax.swing.JTextField();
        jLabelDB4 = new javax.swing.JLabel();
        jComboBoxDB4 = new javax.swing.JComboBox<>();
        jButtonReadDB4 = new javax.swing.JButton();
        jTextFieldDB4 = new javax.swing.JTextField();
        jLabelAddress = new javax.swing.JLabel();
        jLabelConnect = new javax.swing.JLabel();
        jTextAddress = new javax.swing.JTextField();
        jButtonConnect = new javax.swing.JButton();
        jLabelConnectedLed = new javax.swing.JLabel();
        jButtonExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Controlriv GEN3 - S7 protocol tester");

        jPanelledStato.setBackground(java.awt.Color.lightGray);
        jPanelledStato.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelledStato.setName("JPanelStato"); // NOI18N

        jLabelSelectW.setText("Select work ID (DB1 - 110)");
        jLabelSelectW.setToolTipText("");

        jLabelSelectWL.setText("Select worklist ID (DB1 - 150)");
        jLabelSelectWL.setToolTipText("");

        jButtonWriteWork.setBackground(java.awt.Color.cyan);
        jButtonWriteWork.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonWriteWork.setText("Write");
        jButtonWriteWork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonWriteWorkActionPerformed(evt);
            }
        });

        jTextSelectWork.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jButtonWriteWL.setBackground(java.awt.Color.cyan);
        jButtonWriteWL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonWriteWL.setText("Write");
        jButtonWriteWL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonWriteWLActionPerformed(evt);
            }
        });

        jTextSelectWL.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabelStatus.setText("STATUS (OR_FUNC) (DB1 - 100)");

        jTextStatus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextStatus.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextStatus.setDisabledTextColor(java.awt.Color.black);
        jTextStatus.setEnabled(false);

        jTextStatusHEX.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextStatusHEX.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextStatusHEX.setDisabledTextColor(java.awt.Color.black);
        jTextStatusHEX.setEnabled(false);

        jLabel1.setText("decimal");

        jLabel2.setText("HEX");

        jLabelLAV_NO.setText("100 LAV_NO");
        jLabelLAV_NO.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabelLAV_NO.setOpaque(true);

        jLabelLAV_UNC.setText("110 LAV_UNC");
        jLabelLAV_UNC.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabelLAV_UNC.setOpaque(true);

        jLabelLAV_RDY.setText("120 LAV_RDY");
        jLabelLAV_RDY.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabelLAV_RDY.setOpaque(true);

        jLabelLAV_STR.setText("130 LAV_STR");
        jLabelLAV_STR.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabelLAV_STR.setOpaque(true);

        jLabelLAV_DONE.setText("140 LAV_DONE");
        jLabelLAV_DONE.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabelLAV_DONE.setOpaque(true);

        jLabelWL_UNC.setText("150 WL_UNC");
        jLabelWL_UNC.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabelWL_UNC.setOpaque(true);

        jLabelWL_RDY.setText("160 WL_RDY");
        jLabelWL_RDY.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabelWL_RDY.setOpaque(true);

        jLabelWL_STR.setText("170 WL_STR");
        jLabelWL_STR.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabelWL_STR.setOpaque(true);

        jLabelCT_GO.setText("250 CT_GO");
        jLabelCT_GO.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabelCT_GO.setOpaque(true);

        jLabelCT_FLAGAIR_ON.setText("240 CT_FLAGAIR_ON");
        jLabelCT_FLAGAIR_ON.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabelCT_FLAGAIR_ON.setOpaque(true);

        jLabelCT_ALR.setText("230 CT_ALR");
        jLabelCT_ALR.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabelCT_ALR.setOpaque(true);

        jLabelCT_YEL.setText("220 CT_YEL");
        jLabelCT_YEL.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabelCT_YEL.setOpaque(true);

        jLabelCT_LOCK.setText("210 CT_LOCK");
        jLabelCT_LOCK.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabelCT_LOCK.setOpaque(true);

        jLabelCT_RUN.setText("200 CT_RUN");
        jLabelCT_RUN.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabelCT_RUN.setOpaque(true);

        jLabelCT_STOPPD.setText("190 LAV_STOPPD");
        jLabelCT_STOPPD.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabelCT_STOPPD.setOpaque(true);

        jLabelWL_DONE.setText("180 WL_DONE");
        jLabelWL_DONE.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabelWL_DONE.setOpaque(true);

        jLabelRispostaRivettoErr.setText("Answer to incorrectly set rive");

        jButtonRispTiroErrOK.setText("OK");
        jButtonRispTiroErrOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRispTiroErrOKActionPerformed(evt);
            }
        });

        jButtonRispTiroErrAnnulla.setText("X");
        jButtonRispTiroErrAnnulla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRispTiroErrAnnullaActionPerformed(evt);
            }
        });

        jButtonRispTiroErrAccetta.setText(">||");
        jButtonRispTiroErrAccetta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRispTiroErrAccettaActionPerformed(evt);
            }
        });

        jButtonStop.setText("STOP");
        jButtonStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStopActionPerformed(evt);
            }
        });

        jButtonPause.setText("||");
        jButtonPause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPauseActionPerformed(evt);
            }
        });

        jLabelConnectedLedRosso.setBackground(java.awt.Color.lightGray);
        jLabelConnectedLedRosso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabelConnectedLedRosso.setOpaque(true);

        jLabelConnectedLedGiallo.setBackground(java.awt.Color.lightGray);
        jLabelConnectedLedGiallo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabelConnectedLedGiallo.setOpaque(true);

        jLabelConnectedLedVerde.setBackground(java.awt.Color.lightGray);
        jLabelConnectedLedVerde.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabelConnectedLedVerde.setOpaque(true);

        jLabelConnectedLedBlu.setBackground(java.awt.Color.lightGray);
        jLabelConnectedLedBlu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabelConnectedLedBlu.setOpaque(true);

        jLabel3.setText("LED");

        javax.swing.GroupLayout jPanelledStatoLayout = new javax.swing.GroupLayout(jPanelledStato);
        jPanelledStato.setLayout(jPanelledStatoLayout);
        jPanelledStatoLayout.setHorizontalGroup(
            jPanelledStatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelledStatoLayout.createSequentialGroup()
                .addGroup(jPanelledStatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelledStatoLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanelledStatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelledStatoLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(69, 69, 69)
                                .addComponent(jLabel2)
                                .addGap(27, 27, 27))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelledStatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanelledStatoLayout.createSequentialGroup()
                                    .addComponent(jLabelRispostaRivettoErr, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(26, 26, 26)
                                    .addComponent(jButtonRispTiroErrOK, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButtonRispTiroErrAnnulla, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButtonRispTiroErrAccetta, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanelledStatoLayout.createSequentialGroup()
                                    .addGroup(jPanelledStatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelSelectWL, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabelSelectW, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabelStatus, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanelledStatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTextStatus)
                                        .addComponent(jTextSelectWL)
                                        .addComponent(jTextSelectWork, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanelledStatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jButtonWriteWL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonWriteWork, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextStatusHEX, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanelledStatoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addGap(12, 12, 12)
                        .addComponent(jLabelConnectedLedRosso, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelConnectedLedGiallo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelConnectedLedVerde, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelConnectedLedBlu, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelledStatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelledStatoLayout.createSequentialGroup()
                        .addGroup(jPanelledStatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelledStatoLayout.createSequentialGroup()
                                .addGroup(jPanelledStatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabelLAV_RDY, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelLAV_UNC, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelLAV_STR, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelLAV_DONE, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelWL_UNC, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelWL_RDY, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(5, 5, 5)
                                .addGroup(jPanelledStatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelWL_DONE)
                                    .addComponent(jLabelCT_STOPPD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelCT_RUN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelCT_LOCK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelCT_YEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelCT_ALR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelCT_FLAGAIR_ON, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabelLAV_NO)
                            .addGroup(jPanelledStatoLayout.createSequentialGroup()
                                .addComponent(jLabelWL_STR, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelCT_GO, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelledStatoLayout.createSequentialGroup()
                        .addComponent(jButtonStop)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonPause)
                        .addGap(57, 57, 57))))
        );

        jPanelledStatoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabelCT_ALR, jLabelCT_FLAGAIR_ON, jLabelCT_GO, jLabelCT_LOCK, jLabelCT_RUN, jLabelCT_STOPPD, jLabelCT_YEL, jLabelLAV_DONE, jLabelLAV_NO, jLabelLAV_RDY, jLabelLAV_STR, jLabelLAV_UNC, jLabelWL_DONE, jLabelWL_RDY, jLabelWL_STR, jLabelWL_UNC});

        jPanelledStatoLayout.setVerticalGroup(
            jPanelledStatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelledStatoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelledStatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelledStatoLayout.createSequentialGroup()
                        .addGroup(jPanelledStatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelledStatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelStatus)
                            .addComponent(jTextStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextStatusHEX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelledStatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelledStatoLayout.createSequentialGroup()
                                .addGroup(jPanelledStatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelConnectedLedRosso, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelConnectedLedVerde, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelConnectedLedBlu, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanelledStatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButtonRispTiroErrOK)
                                    .addComponent(jButtonRispTiroErrAnnulla)
                                    .addComponent(jButtonRispTiroErrAccetta)
                                    .addComponent(jLabelRispostaRivettoErr))
                                .addGap(48, 48, 48)
                                .addGroup(jPanelledStatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelledStatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextSelectWork, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonWriteWork))
                                    .addComponent(jLabelSelectW)))
                            .addGroup(jPanelledStatoLayout.createSequentialGroup()
                                .addComponent(jLabelConnectedLedGiallo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanelledStatoLayout.createSequentialGroup()
                        .addGap(0, 18, Short.MAX_VALUE)
                        .addGroup(jPanelledStatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelWL_DONE)
                            .addGroup(jPanelledStatoLayout.createSequentialGroup()
                                .addComponent(jLabelLAV_NO)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelledStatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelLAV_UNC)
                                    .addComponent(jLabelCT_STOPPD))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelledStatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelLAV_RDY)
                                    .addComponent(jLabelCT_RUN))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelledStatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelLAV_STR)
                                    .addComponent(jLabelCT_LOCK))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelledStatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelLAV_DONE)
                                    .addComponent(jLabelCT_YEL))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelledStatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelWL_UNC)
                                    .addComponent(jLabelCT_ALR))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelledStatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelWL_RDY)
                                    .addComponent(jLabelCT_FLAGAIR_ON))))
                        .addGap(6, 6, 6)
                        .addGroup(jPanelledStatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelWL_STR)
                            .addComponent(jLabelCT_GO))))
                .addGroup(jPanelledStatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelledStatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextSelectWL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonWriteWL)
                        .addComponent(jButtonStop)
                        .addComponent(jButtonPause))
                    .addComponent(jLabelSelectWL))
                .addContainerGap())
        );

        jLabelDB1.setText("DB1");

        jComboBoxDB1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "100 - Status", "110 - Current Work", "120 - Current batch number in the current job", "130 - Current number of pieces in the job", "140 - Code of the piece chosen in the work", "150 - Current worklist code", "160 - Current repetition number in the worklist", "170 - Current job batch limit", "180 - Current work piece limit", "190 - Repetition limit in the worklist" }));

        jTextFieldDB1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextFieldDB1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldDB1.setDisabledTextColor(java.awt.Color.black);
        jTextFieldDB1.setEnabled(false);

        jButtonReadDB1.setBackground(java.awt.Color.green);
        jButtonReadDB1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonReadDB1.setText("Read");
        jButtonReadDB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReadDB1ActionPerformed(evt);
            }
        });

        jLabelDB2.setText("DB2");

        jComboBoxDB2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "110 - Start work or worklist", "120 - Stop/Abort work or worklist", "130 - Suspend work or worklist", "140 - Reset current job", "150 - Reset current worklist", "160 - Abort last job after an error (corresponds to the “Stop” choice)", "170 - Continue work after an error (corresponds to the “Continue” choice)", "180 - Accept last job after an error (corresponds to the “Accept” choice)", "200 - Cancel processing after an error (corresponds to the “Cancel” choice)", "100 - External block of work", "20   - Reboot Controlriv", "30   - ControlRiv shutdown (WARNING the system will need to be restarted manually)", " ", " " }));

        jButtonWriteDB2.setBackground(java.awt.Color.cyan);
        jButtonWriteDB2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonWriteDB2.setText("Write");
        jButtonWriteDB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonWriteDB2ActionPerformed(evt);
            }
        });

        jTextFieldDB2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextFieldDB2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldDB2.setText("1");
        jTextFieldDB2.setDisabledTextColor(java.awt.Color.black);
        jTextFieldDB2.setEnabled(false);

        jLabelDB3.setText("DB3");

        jComboBoxDB3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10 - Copy Block from PLC", "20 - Copy PLC1 Input - GO ON ANYWAY (the issue will be fixed later)", "30 - Copy PLC2 Input - GO ON (it's not an issue)", "40 - Copy PLC3 Input - IGNORE ACTION and TRY ANOTHER TIME" }));

        jButtonReadDB3.setBackground(java.awt.Color.green);
        jButtonReadDB3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonReadDB3.setText("Read");
        jButtonReadDB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReadDB3ActionPerformed(evt);
            }
        });

        jTextFieldDB3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextFieldDB3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldDB3.setDisabledTextColor(java.awt.Color.black);
        jTextFieldDB3.setEnabled(false);

        jLabelDB4.setText("DB4");

        jComboBoxDB4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10 - Relay related to the green signal", "20 - Relay related to the yellow signal", "30 - Relay related to the red signal", "40 - Relay related to the air ON/OFF state" }));

        jButtonReadDB4.setBackground(java.awt.Color.green);
        jButtonReadDB4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonReadDB4.setText("Read");
        jButtonReadDB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReadDB4ActionPerformed(evt);
            }
        });

        jTextFieldDB4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextFieldDB4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldDB4.setDisabledTextColor(java.awt.Color.black);
        jTextFieldDB4.setEnabled(false);

        jLabelAddress.setText("Address");

        jLabelConnect.setText("Connected");

        jTextAddress.setText("192.168.1.52");

        jButtonConnect.setText("CONNECT");
        jButtonConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConnectActionPerformed(evt);
            }
        });

        jLabelConnectedLed.setBackground(java.awt.Color.red);
        jLabelConnectedLed.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabelConnectedLed.setOpaque(true);

        jButtonExit.setBackground(new java.awt.Color(255, 102, 102));
        jButtonExit.setText("EXIT");
        jButtonExit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabelAddress)
                        .addGap(39, 39, 39)
                        .addComponent(jTextAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jButtonConnect)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelledStato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelDB4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelDB2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelDB1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelDB3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jComboBoxDB4, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jComboBoxDB2, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jComboBoxDB1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jComboBoxDB3, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButtonReadDB4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jButtonWriteDB2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jButtonReadDB1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jButtonReadDB3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabelConnect)
                                        .addGap(51, 51, 51)
                                        .addComponent(jLabelConnectedLed, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(134, 134, 134)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldDB4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldDB3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldDB2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldDB1, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                                    .addComponent(jButtonExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextFieldDB1, jTextFieldDB2, jTextFieldDB3, jTextFieldDB4});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelAddress)
                        .addComponent(jTextAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonConnect)
                        .addComponent(jButtonExit)
                        .addComponent(jLabelConnect))
                    .addComponent(jLabelConnectedLed, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelledStato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDB1)
                    .addComponent(jComboBoxDB1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonReadDB1)
                    .addComponent(jTextFieldDB1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDB2)
                    .addComponent(jComboBoxDB2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonWriteDB2)
                    .addComponent(jTextFieldDB2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabelDB3))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBoxDB3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonReadDB3)
                        .addComponent(jTextFieldDB3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxDB4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDB4)
                    .addComponent(jButtonReadDB4)
                    .addComponent(jTextFieldDB4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonReadDB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReadDB1ActionPerformed
        if (this.jButtonConnect.getText().equals("DISCONNECT")) {
            String rigaScelta = this.jComboBoxDB1.getSelectedItem().toString();
            String[] registroSceltoArray = rigaScelta.split(" ");
            int registroScelto = Integer.parseInt(registroSceltoArray[0]);
            int registroLetto = s7.readInteger(1, registroScelto);
            this.jTextFieldDB1.setText(registroLetto + "");
        }
    }//GEN-LAST:event_jButtonReadDB1ActionPerformed

    private void jButtonReadDB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReadDB3ActionPerformed
        if (this.jButtonConnect.getText().equals("DISCONNECT")) {
            String rigaScelta = this.jComboBoxDB3.getSelectedItem().toString();
            String[] registroSceltoArray = rigaScelta.split(" ");
            int registroScelto = Integer.parseInt(registroSceltoArray[0]);
            int registroLetto = s7.readInteger(3, registroScelto);
            this.jTextFieldDB3.setText(registroLetto + "");
        }
    }//GEN-LAST:event_jButtonReadDB3ActionPerformed

    private void jButtonReadDB4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReadDB4ActionPerformed
        if (this.jButtonConnect.getText().equals("DISCONNECT")) {
            String rigaScelta = this.jComboBoxDB4.getSelectedItem().toString();
            String[] registroSceltoArray = rigaScelta.split(" ");
            int registroScelto = Integer.parseInt(registroSceltoArray[0]);
            int registroLetto = s7.readInteger(4, registroScelto);
            this.jTextFieldDB4.setText(registroLetto + "");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonReadDB4ActionPerformed

    private void jButtonConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConnectActionPerformed
        if (this.jButtonConnect.getText().equals("CONNECT")) {
            s7.setCRIV_IP(this.jTextAddress.getText());
            s7.connectCRIV();
            if (s7.getConnectStatus() == 0) {
                startTimer();
                this.jLabelConnectedLed.setBackground(Color.green);
                this.jButtonConnect.setText("DISCONNECT");
                this.jTextSelectWork.setEnabled(true);
                this.jTextSelectWL.setEnabled(true);
                this.jButtonWriteWork.setEnabled(true);
                this.jButtonWriteWL.setEnabled(true);
                this.jButtonReadDB1.setEnabled(true);
                this.jButtonWriteDB2.setEnabled(true);
                this.jButtonReadDB3.setEnabled(true);
                this.jButtonReadDB4.setEnabled(true);
            }
        } else {
            this.jLabelConnectedLed.setBackground(Color.red);
            this.jButtonConnect.setText("CONNECT");
            this.jTextSelectWork.setEnabled(false);
            this.jTextSelectWL.setEnabled(false);
            this.jButtonWriteWork.setEnabled(false);
            this.jButtonWriteWL.setEnabled(false);
            this.jButtonReadDB1.setEnabled(false);
            this.jButtonWriteDB2.setEnabled(false);
            this.jButtonReadDB3.setEnabled(false);
            this.jButtonReadDB4.setEnabled(false);
            this.jTextStatus.setText("");
            this.jTextStatusHEX.setText("");
            s7.disconnectCRIV();
        }
    }//GEN-LAST:event_jButtonConnectActionPerformed

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        if (this.jButtonConnect.getText().equals("DISCONNECT")) {
            this.jButtonConnect.setText("CONNECT");
            this.jLabelConnectedLed.setBackground(Color.red);
            s7.disconnectCRIV();
        }
        System.exit(0);
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButtonWriteWorkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonWriteWorkActionPerformed
        if (this.jButtonConnect.getText().equals("DISCONNECT")) {
            int workID = Integer.parseInt(this.jTextSelectWork.getText());
            s7.writeInteger(DB1, 110, workID);
        }
    }//GEN-LAST:event_jButtonWriteWorkActionPerformed

    private void jButtonWriteWLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonWriteWLActionPerformed
        if (this.jButtonConnect.getText().equals("DISCONNECT")) {
            int workWL = Integer.parseInt(this.jTextSelectWL.getText());
            s7.writeInteger(DB1, 150, workWL);
        }
    }//GEN-LAST:event_jButtonWriteWLActionPerformed

    private void jButtonWriteDB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonWriteDB2ActionPerformed
        if (this.jButtonConnect.getText().equals("DISCONNECT")) {
            String rigaScelta = this.jComboBoxDB2.getSelectedItem().toString();
            String[] registroSceltoArray = rigaScelta.split(" ");
            int registroScelto = Integer.parseInt(registroSceltoArray[0]);
            //int valoreScritto = Integer.parseInt(this.jTextFieldDB2.getText());
            byte valoreScritto = Byte.parseByte(this.jTextFieldDB2.getText());
            s7.writeByte(DB2, registroScelto, valoreScritto);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonWriteDB2ActionPerformed

    private void jButtonRispTiroErrOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRispTiroErrOKActionPerformed
        // Risposta Tiro Errato
        s7.writeInteger(DB2, 180, Byte.parseByte("1"));
    }//GEN-LAST:event_jButtonRispTiroErrOKActionPerformed

    private void jButtonRispTiroErrAnnullaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRispTiroErrAnnullaActionPerformed
        // Risposta Tiro Errato
        s7.writeInteger(DB2, 200, Byte.parseByte("1"));
    }//GEN-LAST:event_jButtonRispTiroErrAnnullaActionPerformed

    private void jButtonRispTiroErrAccettaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRispTiroErrAccettaActionPerformed
        // Risposta Tiro Errato
        s7.writeInteger(DB2, 170, Byte.parseByte("1"));
    }//GEN-LAST:event_jButtonRispTiroErrAccettaActionPerformed

    private void jButtonStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStopActionPerformed
        // Risposta Tiro Errato
        s7.writeInteger(DB2, 120, Byte.parseByte("1"));
    }//GEN-LAST:event_jButtonStopActionPerformed

    private void jButtonPauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPauseActionPerformed
        // Risposta Tiro Errato
        s7.writeInteger(DB2, 130, Byte.parseByte("1"));
    }//GEN-LAST:event_jButtonPauseActionPerformed

    private void startTimer() {
        timer = new Timer();

        timer.scheduleAtFixedRate(new TimerTask() {
            @Override
            public void run() {

                if (!jButtonConnect.getText().equals("DISCONNECT")) {
                    return;
                }

                int registroLetto = s7.readInteger(1, 100);

                SwingUtilities.invokeLater(() -> {
                    jTextStatus.setText(String.valueOf(registroLetto));
                    jTextStatusHEX.setText(String.format("0x%06X", registroLetto));
                    updateSingoliRegistri();
                    int LettoStatoLedVerde = s7.readInteger(DB4, 10);
                    int LettoStatoLedGiallo = s7.readInteger(DB4, 20);
                    int LettoStatoLedRosso = s7.readInteger(DB4, 30);
                    int LettoStatoLedAria = s7.readInteger(DB4, 40);
                    if (LettoStatoLedRosso == 1) {
                        jLabelConnectedLedRosso.setBackground(Color.red);
                    } else {
                        jLabelConnectedLedRosso.setBackground(Color.lightGray);
                    }
                    if (LettoStatoLedVerde == 1) {
                        jLabelConnectedLedVerde.setBackground(Color.green);
                    } else {
                        jLabelConnectedLedVerde.setBackground(Color.lightGray);
                    }
                    if (LettoStatoLedGiallo == 1) {
                        jLabelConnectedLedGiallo.setBackground(Color.yellow);
                    } else {
                        jLabelConnectedLedGiallo.setBackground(Color.lightGray);
                    }
                    if (LettoStatoLedAria == 1) {
                        jLabelConnectedLedBlu.setBackground(Color.blue);
                    } else {
                        jLabelConnectedLedBlu.setBackground(Color.lightGray);
                    }                    
                });
            }
        }, 0L, 500L);
    }

    private void updateSingoliRegistri() {
        for (int i = 0; i < 16; i++) {
            //int regLetto = this.s7.readInteger(4, 100 + i * 10);
            int regLetto = s7.readInteger(DB4, 100 + i * 10);

            if (regLetto == 1) {
                switch (i) {
                    case 0 ->
                        this.jLabelLAV_NO.setBackground(Color.green);
                    case 1 ->
                        this.jLabelLAV_UNC.setBackground(Color.green);
                    case 2 ->
                        this.jLabelLAV_RDY.setBackground(Color.green);
                    case 3 ->
                        this.jLabelLAV_STR.setBackground(Color.green);
                    case 4 ->
                        this.jLabelLAV_DONE.setBackground(Color.blue);
                    case 5 ->
                        this.jLabelWL_UNC.setBackground(Color.green);
                    case 6 ->
                        this.jLabelWL_RDY.setBackground(Color.green);
                    case 7 ->
                        this.jLabelWL_STR.setBackground(Color.green);
                    case 8 ->
                        this.jLabelWL_DONE.setBackground(Color.blue);
                    case 9 ->
                        this.jLabelCT_STOPPD.setBackground(Color.green);
                    case 10 ->
                        this.jLabelCT_RUN.setBackground(Color.green);
                    case 11 ->
                        this.jLabelCT_LOCK.setBackground(Color.red);
                    case 12 ->
                        this.jLabelCT_YEL.setBackground(Color.yellow);
                    case 13 ->
                        this.jLabelCT_ALR.setBackground(Color.red);
                    case 14 ->
                        this.jLabelCT_FLAGAIR_ON.setBackground(Color.green);
                    case 15 ->
                        this.jLabelCT_GO.setBackground(Color.green);
                }
            } else {
                switch (i) {
                    case 0 ->
                        this.jLabelLAV_NO.setBackground(Color.white);
                    case 1 ->
                        this.jLabelLAV_UNC.setBackground(Color.white);
                    case 2 ->
                        this.jLabelLAV_RDY.setBackground(Color.white);
                    case 3 ->
                        this.jLabelLAV_STR.setBackground(Color.white);
                    case 4 ->
                        this.jLabelLAV_DONE.setBackground(Color.white);
                    case 5 ->
                        this.jLabelWL_UNC.setBackground(Color.white);
                    case 6 ->
                        this.jLabelWL_RDY.setBackground(Color.white);
                    case 7 ->
                        this.jLabelWL_STR.setBackground(Color.white);
                    case 8 ->
                        this.jLabelWL_DONE.setBackground(Color.white);
                    case 9 ->
                        this.jLabelCT_STOPPD.setBackground(Color.white);
                    case 10 ->
                        this.jLabelCT_RUN.setBackground(Color.white);
                    case 11 ->
                        this.jLabelCT_LOCK.setBackground(Color.white);
                    case 12 ->
                        this.jLabelCT_YEL.setBackground(Color.white);
                    case 13 ->
                        this.jLabelCT_ALR.setBackground(Color.white);
                    case 14 ->
                        this.jLabelCT_FLAGAIR_ON.setBackground(Color.white);
                    case 15 ->
                        this.jLabelCT_GO.setBackground(Color.white);
                }
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JConsole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JConsole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JConsole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JConsole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {

                new JConsole().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConnect;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonPause;
    private javax.swing.JButton jButtonReadDB1;
    private javax.swing.JButton jButtonReadDB3;
    private javax.swing.JButton jButtonReadDB4;
    private javax.swing.JButton jButtonRispTiroErrAccetta;
    private javax.swing.JButton jButtonRispTiroErrAnnulla;
    private javax.swing.JButton jButtonRispTiroErrOK;
    private javax.swing.JButton jButtonStop;
    private javax.swing.JButton jButtonWriteDB2;
    private javax.swing.JButton jButtonWriteWL;
    private javax.swing.JButton jButtonWriteWork;
    private javax.swing.JComboBox<String> jComboBoxDB1;
    private javax.swing.JComboBox<String> jComboBoxDB2;
    private javax.swing.JComboBox<String> jComboBoxDB3;
    private javax.swing.JComboBox<String> jComboBoxDB4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelAddress;
    private javax.swing.JLabel jLabelCT_ALR;
    private javax.swing.JLabel jLabelCT_FLAGAIR_ON;
    private javax.swing.JLabel jLabelCT_GO;
    private javax.swing.JLabel jLabelCT_LOCK;
    private javax.swing.JLabel jLabelCT_RUN;
    private javax.swing.JLabel jLabelCT_STOPPD;
    private javax.swing.JLabel jLabelCT_YEL;
    private javax.swing.JLabel jLabelConnect;
    private javax.swing.JLabel jLabelConnectedLed;
    private javax.swing.JLabel jLabelConnectedLedBlu;
    private javax.swing.JLabel jLabelConnectedLedGiallo;
    private javax.swing.JLabel jLabelConnectedLedRosso;
    private javax.swing.JLabel jLabelConnectedLedVerde;
    private javax.swing.JLabel jLabelDB1;
    private javax.swing.JLabel jLabelDB2;
    private javax.swing.JLabel jLabelDB3;
    private javax.swing.JLabel jLabelDB4;
    private javax.swing.JLabel jLabelLAV_DONE;
    private javax.swing.JLabel jLabelLAV_NO;
    private javax.swing.JLabel jLabelLAV_RDY;
    private javax.swing.JLabel jLabelLAV_STR;
    private javax.swing.JLabel jLabelLAV_UNC;
    private javax.swing.JLabel jLabelRispostaRivettoErr;
    private javax.swing.JLabel jLabelSelectW;
    private javax.swing.JLabel jLabelSelectWL;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JLabel jLabelWL_DONE;
    private javax.swing.JLabel jLabelWL_RDY;
    private javax.swing.JLabel jLabelWL_STR;
    private javax.swing.JLabel jLabelWL_UNC;
    private javax.swing.JPanel jPanelledStato;
    private javax.swing.JTextField jTextAddress;
    private javax.swing.JTextField jTextFieldDB1;
    private javax.swing.JTextField jTextFieldDB2;
    private javax.swing.JTextField jTextFieldDB3;
    private javax.swing.JTextField jTextFieldDB4;
    private javax.swing.JTextField jTextSelectWL;
    private javax.swing.JTextField jTextSelectWork;
    private javax.swing.JTextField jTextStatus;
    private javax.swing.JTextField jTextStatusHEX;
    // End of variables declaration//GEN-END:variables
}
